# -*- coding: utf-8 -*-
"""Data Analysis Testing

Originally generated by Colab; exported to a standalone script.
"""

# Commented out IPython magic to ensure Python compatibility.
# # Prevents long outputs
# %%capture
# !pip install cartopy
# !pip install adjustText

import xarray as xr
import os
import os.path as osp
import json

# Visualizing
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import numpy as np
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from adjustText import adjust_text
import contextlib
import sys

# Path to the data directory. Override with the DATA_ROOT_DIR environment
# variable, or edit this default to point at your local copy.
data_root_dir = os.environ.get("DATA_ROOT_DIR", "Run2045_Moderate_GoDEEEP_hourly")
data_no_tx_dir = osp.join(data_root_dir, "Results – No transmission expansion") # Without transmission expansion)
data_tx_dir = osp.join(data_root_dir, "Results – Transmission expansion possible") # With transmission expansion

data_files = [ # The json and .nc files have the same names. Transmission expansion files have extra _xtrans suffix
    "A_co2_00_hourly",
    "A_co2_05_hourly",
    "A_co2_20_hourly",
    "A_co2_50_hourly",
    "A_co2_100_hourly"
]
tx_suffix = "_xtrans"

# Grabbing the data (using xarrays instead of pypsa networks)
data_notx = {}
data_tx = {}
for file_name in data_files:
  # Grab no transmission expansion data first
  key = file_name.split("_")[-2]
  if key == "100":
    value = {"nc": xr.open_dataset(osp.join(data_no_tx_dir, file_name + "_monthly_noCCS.nc"))}
    with open(osp.join(data_no_tx_dir, file_name + "_monthly_noCCS.json")) as f:
      value["json"] = json.load(f)
  else:
    value = {"nc": xr.open_dataset(osp.join(data_no_tx_dir, file_name + ".nc"))}
    with open(osp.join(data_no_tx_dir, file_name + ".json")) as f:
      value["json"] = json.load(f)
  data_notx[key] = value

  # Grab transmission expansion data
  value = {"nc": xr.open_dataset(osp.join(data_tx_dir, file_name + "_xtrans.nc"))}
  with open(osp.join(data_tx_dir, file_name + "_xtrans.json")) as f:
    value["json"] = json.load(f)
  data_tx[key] = value

# Combining the two
data = {
    "no_tx": data_notx,
    "tx": data_tx
}

# 3. Data Access - Modify these to change scenario
def plot(tx_type, co2_limit):

  nc = data[tx_type][co2_limit]['nc']

  # 4. Dynamic Title
  if tx_type == 'tx':
    txm_title = "Expandable"
  else:
    txm_title = "Static"
  title_str = f"Scenario {co2_limit}% CO2 | Transmission: {txm_title}"

  # Pre-calculations
  bus_gen_data = {}
  all_carriers = set()

  # Collecting information for all buses
  for bus in nc['buses_i'].values:
      # Pick all generators at this bus
      gens_mask = (nc['generators_bus'] == bus)
      gen_ids = nc['generators_i'].where(gens_mask, drop=True).values

      gen_mix = {} # Find the top generation carriers
      if len(gen_ids) > 0:
          for g_id in gen_ids:
              carrier = nc['generators_carrier'].sel(generators_i=g_id).item() # Get production type at this generator
              if g_id in nc['generators_t_p_i'].values: # If this generator is actually producing energy
                  prod = max(0, nc['generators_t_p'].sel(generators_t_p_i=g_id).sum().item() / 1e3) # Add it only if energy > 0
                  gen_mix[carrier] = gen_mix.get(carrier, 0) + prod
                  all_carriers.add(carrier)

      sorted_mix = sorted(gen_mix.items(), key=lambda x: x[1], reverse=True)[:4] # Grab top 4 energy
      total_bus_gen = sum(v for k, v in sorted_mix)

      p_nom = nc['generators_p_nom'].sel(generators_i=gen_ids).sum().item() if len(gen_ids) else 0.0
      p_nom_opt = nc['generators_p_nom_opt'].sel(generators_i=gen_ids).sum().item() if len(gen_ids) else 0.0
      added_cap_mw = p_nom_opt - p_nom
      if total_bus_gen == 0:
        # Hacky way to get a pie chart. I think this happens when so little generation is needed
        sorted_mix = set((k, 1) for k, v in sorted_mix)

      bus_gen_data[bus] = {'total': total_bus_gen, 'added': added_cap_mw, 'mix': sorted_mix}

  # Consistent Color Mapping for Legend
  carrier_colors = {c: plt.cm.tab20(i % 20) for i, c in enumerate(sorted(list(all_carriers)))}
  texts = []

  fig = plt.figure(figsize=(18, 10))
  ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
  ax.set_extent([-126, -100, 31, 49], crs=ccrs.PlateCarree())
  ax.add_feature(cfeature.LAND, facecolor='#f9f9f9')
  ax.add_feature(cfeature.COASTLINE, linewidth=1)
  ax.add_feature(cfeature.STATES, edgecolor='gray', alpha=0.3)

  node_x, node_y = nc['buses_x'], nc['buses_y']

  pie_r = 0.2
  for bus in nc['buses_i'].values:
      x, y = node_x.sel(buses_i=bus).item(), node_y.sel(buses_i=bus).item()
      info = bus_gen_data[bus]

      vals = [v for k, v in info['mix']]
      if len(vals) == 0:
        # Plot a black dot
        ax.scatter(x, y, s=10, transform=ccrs.PlateCarree(), color='black')
      else:
        colors = [carrier_colors[k] for k, v in info['mix']]

        # Create inset axes centered at map coordinate
        ax_sub = inset_axes(
            ax,
            width=pie_r * 2,
            height=pie_r * 2,
            loc='center',
            bbox_to_anchor=(x, y),
            bbox_transform=ax.transData,
            borderpad=0
        )

        ax_sub.pie(
            vals,
            colors=colors,
            wedgeprops={
                'edgecolor': 'white',
                'linewidth': 1
            }
        )

      ax_sub.set_aspect('equal')
      ax_sub.axis('off')

      # Larger text labels for nodes
      # Manual adjustments
      text_x, text_y = x, y
      if bus in ['p2', 'p5', 'p6', 'p9', 'p10']:
        # Move left
        text_x -= 1.8
        text_y -= 0.3
      elif bus in ['p30', 'p11', 'p33', 'p34', 'p31', 'p59', 'p15']:
        # Move right
        text_x += 1
      elif bus in ['p1', 'p23']:
        # Move up left
        text_x -= 1
        text_y += 1.1
      elif bus in ['p25']:
        # Up left, but not so up, more left
        text_x -= 1.5
        text_y += 0.6
      elif bus in ['p21', 'p27', 'p13', 'p3', 'p16']:
        # Move up right
        text_x += 0.5
        text_y += 0.5
      elif bus in ['p26', 'p24']:
        text_x += 0.9
        text_y += 0.3
      elif bus in ['p22']:
        # Move up higher
        text_y += 1
      elif bus in ['p7']:
        # Move down
        text_y -= 1.3
      else:
        text_y += 0.6
      texts.append(ax.text(text_x, text_y, f"{bus}\n\u0394:{info['added']:.0f} MW\nTot:{info['total']:.1f} MW"
              , fontsize=6,
              ha='center', bbox=dict(facecolor='white', alpha=0.85, boxstyle='round,pad=0.3'),
              transform=ccrs.PlateCarree(), zorder=15))

  # Transmission expansion labels
  if 'links_bus0' in nc:
      for i in range(len(nc['links_i'])):
          expansion = nc['links_p_nom_opt'].isel(links_i=i).item() - nc['links_p_nom'].isel(links_i=i).item()
          b0, b1 = nc['links_bus0'].isel(links_i=i).item(), nc['links_bus1'].isel(links_i=i).item()
          x0, y0 = node_x.sel(buses_i=b0).item(), node_y.sel(buses_i=b0).item()
          x1, y1 = node_x.sel(buses_i=b1).item(), node_y.sel(buses_i=b1).item()
          dx = x1 - x0
          dy = y1 - y0
          dist = np.sqrt(dx**2 + dy**2)

          # unit direction vector
          ux, uy = dx / dist, dy / dist

          # shrink both ends by pie radius
          x0_adj = x0 + ux * pie_r
          y0_adj = y0 + uy * pie_r

          x1_adj = x1 - ux * pie_r
          y1_adj = y1 - uy * pie_r
          # Draw an arrow
          ax.annotate(
              "",
              xy=(x1_adj, y1_adj),
              xytext=(x0_adj, y0_adj),
              arrowprops=dict(
                  arrowstyle="->",
                  color="orange",
                  lw=2
              ),
              transform=ccrs.PlateCarree()
          )
          t = 0.6
          if expansion != 0:
            texts.append(ax.text(x0 + t*(x1-x0), y0 + t*(y1 - y0), f"{expansion:.0f}", fontsize=6,
                    fontweight='black', transform=ccrs.PlateCarree(), zorder=20,
                    bbox=dict(facecolor='yellow', alpha=0.9, pad=1, edgecolor='none')))

  # Create a manual legend for the carriers
  legend_elements = [Patch(facecolor=carrier_colors[c], label=c) for c in sorted(all_carriers)] + [Patch(facecolor='yellow', label="Added Transmission (MW)")]
  ax.legend(handles=legend_elements, loc='upper right', title="Generation Mix (Top 4)",
            fontsize=8, title_fontsize=8, framealpha=1.0, edgecolor='black')

  ax.set_title(title_str, fontsize=18, pad=10, fontweight='bold')

  # Adjust the text to prevent overlap
  with contextlib.redirect_stdout(None):
    adjust_text(
        texts,
        ax=ax,
        expand_text=(1.0, 1),
        expand_points=(1, 1),
        force_text=(0.5, 1.0),
        force_points=(0.5, 1.0),
        arrowprops=dict(
            arrowstyle="-",
            color='gray',
            lw=0.5
        )
    )

  plt.show()

tx_type = 'no_tx'
for co2_limit in ['100', '50', '20', '05', '00']:
  plot(tx_type, co2_limit)

